import type { ArtifactRecord } from "../chatbot/types"

export const ARTIFACTS: ArtifactRecord[] = [
  // ─── Wood ────────────────────────────────────────────────────
  {
    id: "artifact-wood-001",
    nameAr: "تابوت خشبي مزخرف",
    nameEn: "Decorated Wooden Coffin",
    material: "wood",
    subType: "تابوت",
    era: "middle-kingdom",
    dynasty: 12,
    approximateDate: "حوالي 1900 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    dimensions: "200 × 60 × 60 سم",
    condition: "good",
    description:
      "تابوت خشبي مزخرف بنصوص التوابيت والزخارف الهندسية الملونة، يعكس الاعتقادات الدينية في الدولة الوسطى.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-wood-002",
    nameAr: "مشربية خشبية إسلامية",
    nameEn: "Islamic Wooden Mashrabiya",
    material: "wood",
    subType: "مشربية",
    era: "islamic",
    approximateDate: "القرن الثالث عشر الميلادي",
    museum: "متحف الفن الإسلامي",
    museumLocation: "القاهرة، مصر",
    dimensions: "150 × 80 سم",
    condition: "excellent",
    description:
      "مشربية خشبية مخرمة بزخارف هندسية إسلامية دقيقة، تُستخدم في النوافذ لتلطيف الهواء وتوفير الخصوصية.",
    imageUrl: undefined,
    relatedPageLink: "/era/islamic/mashrabiya",
  },
  {
    id: "artifact-wood-003",
    nameAr: "كرسي توت عنخ آمون",
    nameEn: "Tutankhamun's Throne Chair",
    material: "wood",
    subType: "أثاث ملكي",
    era: "new-kingdom",
    dynasty: 18,
    approximateDate: "حوالي 1330 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    condition: "excellent",
    description:
      "كرسي عرش ملكي مصنوع من الخشب المطعّم بالذهب والعاج والأحجار الكريمة، من كنوز مقبرة توت عنخ آمون.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },

  // ─── Metal ───────────────────────────────────────────────────
  {
    id: "artifact-metal-001",
    nameAr: "قناع توت عنخ آمون الذهبي",
    nameEn: "Golden Death Mask of Tutankhamun",
    material: "metal",
    subType: "قناع جنائزي",
    era: "new-kingdom",
    dynasty: 18,
    approximateDate: "حوالي 1323 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    dimensions: "54 × 39.3 سم",
    condition: "excellent",
    description:
      "قناع جنائزي ذهبي خالص مرصّع بالأحجار الكريمة والزجاج الملون، يُعدّ من أشهر القطع الأثرية في العالم.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-metal-002",
    nameAr: "سيف رمسيس الثاني",
    nameEn: "Sword of Ramesses II",
    material: "metal",
    subType: "سلاح",
    era: "new-kingdom",
    dynasty: 19,
    approximateDate: "حوالي 1270 ق.م",
    museum: "متحف اللوفر",
    museumLocation: "باريس، فرنسا",
    condition: "good",
    description: "سيف برونزي ملكي مزخرف بنقوش هيروغليفية تمجّد انتصارات رمسيس الثاني.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-metal-003",
    nameAr: "مجوهرات تانيس الذهبية",
    nameEn: "Gold Jewelry of Tanis",
    material: "metal",
    subType: "مجوهرات ملكية",
    era: "third-intermediate",
    dynasty: 21,
    approximateDate: "حوالي 1000 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    condition: "excellent",
    description:
      "مجموعة من المجوهرات الذهبية الملكية المكتشفة في مقابر تانيس، تشمل أطواق وأساور وخواتم مرصّعة بالأحجار الكريمة.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },

  // ─── Stone ───────────────────────────────────────────────────
  {
    id: "artifact-stone-001",
    nameAr: "حجر رشيد",
    nameEn: "Rosetta Stone",
    material: "stone",
    subType: "لوح نقشي",
    era: "greco-roman",
    approximateDate: "196 ق.م",
    museum: "المتحف البريطاني",
    museumLocation: "لندن، المملكة المتحدة",
    dimensions: "114 × 72 × 28 سم",
    condition: "good",
    description:
      "لوح حجري من الجرانوديوريت يحمل مرسوم بطليموس الخامس بثلاث لغات: الهيروغليفية والديموطيقية واليونانية، كان مفتاح فك رموز الهيروغليفية.",
    imageUrl: undefined,
    relatedPageLink: "/era/greco-roman",
  },
  {
    id: "artifact-stone-002",
    nameAr: "تمثال خفرع",
    nameEn: "Statue of Khafre",
    material: "stone",
    subType: "تمثال ملكي",
    era: "old-kingdom",
    dynasty: 4,
    approximateDate: "حوالي 2530 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    dimensions: "168 سم ارتفاع",
    condition: "excellent",
    description:
      "تمثال من الديوريت الأسود يصوّر الفرعون خفرع جالساً على عرشه محمياً بصقر حورس، يُعدّ من روائع النحت المصري القديم.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-stone-003",
    nameAr: "لوحة نارمر",
    nameEn: "Narmer Palette",
    material: "stone",
    subType: "لوحة طقسية",
    era: "early-dynastic",
    dynasty: 1,
    approximateDate: "حوالي 3100 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    dimensions: "64 × 42 سم",
    condition: "good",
    description:
      "لوحة من الحجر الرملي تصوّر الفرعون نارمر موحّداً مصر العليا والسفلى، تُعدّ من أقدم الوثائق التاريخية في العالم.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },

  // ─── Pottery ─────────────────────────────────────────────────
  {
    id: "artifact-pottery-001",
    nameAr: "إناء فخاري نقادة",
    nameEn: "Naqada Pottery Vessel",
    material: "pottery",
    subType: "إناء",
    era: "predynastic",
    approximateDate: "حوالي 3500 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    condition: "good",
    description:
      "إناء فخاري مزخرف بزخارف هندسية وأشكال حيوانية، يمثّل ذروة الفخار في عصر نقادة الثانية.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-pottery-002",
    nameAr: "جرة كانوبية",
    nameEn: "Canopic Jar",
    material: "pottery",
    subType: "وعاء جنائزي",
    era: "new-kingdom",
    dynasty: 18,
    approximateDate: "حوالي 1350 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    condition: "excellent",
    description:
      "جرة كانوبية من الفخار المطلي تُستخدم لحفظ أحشاء المتوفى أثناء التحنيط، غطاؤها على شكل رأس ابن آوى.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },

  // ─── Papyrus ─────────────────────────────────────────────────
  {
    id: "artifact-papyrus-001",
    nameAr: "بردية إيبرس الطبية",
    nameEn: "Ebers Papyrus",
    material: "papyrus",
    subType: "مخطوطة طبية",
    era: "new-kingdom",
    dynasty: 18,
    approximateDate: "حوالي 1550 ق.م",
    museum: "مكتبة جامعة لايبزيغ",
    museumLocation: "لايبزيغ، ألمانيا",
    dimensions: "20 متر طولاً",
    condition: "good",
    description:
      "أقدم وأشمل وثيقة طبية في التاريخ، تحتوي على 700 وصفة طبية وعلاجات لأمراض متعددة، تعكس تقدم الطب المصري القديم.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-papyrus-002",
    nameAr: "بردية قصة سنوهي",
    nameEn: "Story of Sinuhe Papyrus",
    material: "papyrus",
    subType: "أدب",
    era: "middle-kingdom",
    dynasty: 12,
    approximateDate: "حوالي 1900 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    condition: "fair",
    description:
      "من أشهر الأعمال الأدبية في مصر القديمة، تحكي قصة مسؤول مصري يهرب إلى بلاد الشام ثم يعود إلى وطنه.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },

  // ─── Jewelry ─────────────────────────────────────────────────
  {
    id: "artifact-jewelry-001",
    nameAr: "قلادة الأميرة ست حتحور",
    nameEn: "Princess Sithathoryunet's Necklace",
    material: "jewelry",
    subType: "قلادة",
    era: "middle-kingdom",
    dynasty: 12,
    approximateDate: "حوالي 1887 ق.م",
    museum: "متحف المتروبوليتان",
    museumLocation: "نيويورك، الولايات المتحدة",
    condition: "excellent",
    description:
      "قلادة ذهبية مرصّعة بالعقيق والفيروز واللازورد، تُعدّ من أجمل المجوهرات المصرية القديمة وأكثرها تعقيداً.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-jewelry-002",
    nameAr: "خاتم الجعران الملكي",
    nameEn: "Royal Scarab Ring",
    material: "jewelry",
    subType: "خاتم",
    era: "new-kingdom",
    dynasty: 18,
    approximateDate: "حوالي 1400 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    condition: "excellent",
    description:
      "خاتم ذهبي على شكل جعران مقدس، يُعدّ رمزاً للبعث والتجدد في الديانة المصرية القديمة.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },

  // ─── Statues ─────────────────────────────────────────────────
  {
    id: "artifact-statues-001",
    nameAr: "تمثال خوفو العاجي",
    nameEn: "Ivory Statuette of Khufu",
    material: "statues",
    subType: "تمثال صغير",
    era: "old-kingdom",
    dynasty: 4,
    approximateDate: "حوالي 2580 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    dimensions: "7.5 سم ارتفاع",
    condition: "good",
    description:
      "التمثال الوحيد المعروف للفرعون خوفو باني الهرم الأكبر، مصنوع من العاج ويُصوّره جالساً على عرشه.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-statues-002",
    nameAr: "تمثال نفرتيتي",
    nameEn: "Bust of Nefertiti",
    material: "statues",
    subType: "نصف تمثال",
    era: "new-kingdom",
    dynasty: 18,
    approximateDate: "حوالي 1345 ق.م",
    museum: "متحف نيوس",
    museumLocation: "برلين، ألمانيا",
    dimensions: "50 سم ارتفاع",
    condition: "excellent",
    description:
      "نصف تمثال من الحجر الجيري المطلي يصوّر الملكة نفرتيتي، يُعدّ من أشهر الأعمال الفنية في التاريخ.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },

  // ─── Furniture ───────────────────────────────────────────────
  {
    id: "artifact-furniture-001",
    nameAr: "سرير توت عنخ آمون",
    nameEn: "Tutankhamun's Ceremonial Bed",
    material: "furniture",
    subType: "سرير طقسي",
    era: "new-kingdom",
    dynasty: 18,
    approximateDate: "حوالي 1330 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    condition: "excellent",
    description:
      "سرير طقسي مصنوع من الخشب المطلي بالذهب على شكل حيوانات مقدسة، من كنوز مقبرة توت عنخ آمون.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-furniture-002",
    nameAr: "صندوق خشبي مزخرف",
    nameEn: "Decorated Wooden Chest",
    material: "furniture",
    subType: "صندوق",
    era: "new-kingdom",
    dynasty: 18,
    approximateDate: "حوالي 1350 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    condition: "good",
    description:
      "صندوق خشبي مطعّم بالعاج والأبنوس بزخارف ملونة تصوّر مشاهد الصيد والحرب، من كنوز مقبرة توت عنخ آمون.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },

  // ─── Textile ─────────────────────────────────────────────────
  {
    id: "artifact-textile-001",
    nameAr: "كتان ملكي مطرز",
    nameEn: "Royal Embroidered Linen",
    material: "textile",
    subType: "قماش ملكي",
    era: "new-kingdom",
    dynasty: 18,
    approximateDate: "حوالي 1350 ق.م",
    museum: "المتحف المصري",
    museumLocation: "القاهرة، مصر",
    condition: "fair",
    description:
      "قطعة من الكتان الملكي المطرز بخيوط الذهب والألوان الزاهية، تُصوّر مشاهد دينية وملكية.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-textile-002",
    nameAr: "نسيج قبطي مزخرف",
    nameEn: "Decorated Coptic Textile",
    material: "textile",
    subType: "نسيج قبطي",
    era: "greco-roman",
    approximateDate: "القرن الرابع الميلادي",
    museum: "متحف الفن القبطي",
    museumLocation: "القاهرة، مصر",
    condition: "good",
    description:
      "نسيج قبطي مزخرف بزخارف هندسية ونباتية ملونة، يجمع بين التقاليد المصرية والبيزنطية.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },

  // ─── Glass ───────────────────────────────────────────────────
  {
    id: "artifact-glass-001",
    nameAr: "كوب زجاجي ملون",
    nameEn: "Colored Glass Vessel",
    material: "glass",
    subType: "إناء زجاجي",
    era: "new-kingdom",
    dynasty: 18,
    approximateDate: "حوالي 1400 ق.م",
    museum: "المتحف البريطاني",
    museumLocation: "لندن، المملكة المتحدة",
    dimensions: "12 سم ارتفاع",
    condition: "good",
    description:
      "إناء زجاجي ملون بتقنية الخيوط الزجاجية الملتوية، يُعدّ من أقدم الأمثلة على صناعة الزجاج في مصر القديمة.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
  {
    id: "artifact-glass-002",
    nameAr: "قارورة زجاجية فاطمية",
    nameEn: "Fatimid Glass Bottle",
    material: "glass",
    subType: "قارورة",
    era: "islamic",
    approximateDate: "القرن الحادي عشر الميلادي",
    museum: "متحف الفن الإسلامي",
    museumLocation: "القاهرة، مصر",
    condition: "good",
    description:
      "قارورة زجاجية شفافة مزخرفة بنقوش محفورة تصوّر حيوانات وزخارف نباتية، من روائع الزجاج الفاطمي.",
    imageUrl: undefined,
    relatedPageLink: undefined,
  },
]
