import type { EraRecord } from "../chatbot/types"

export const ERAS: EraRecord[] = [
  {
    id: "predynastic",
    nameAr: "عصر ما قبل الأسرات",
    nameEn: "Predynastic Period",
    startYear: -6000,
    endYear: -3100,
    dynasties: [],
    description:
      "المرحلة التأسيسية للحضارة المصرية قبل توحيد البلاد، شهدت نشوء المجتمعات الزراعية وتطور الفنون والحرف اليدوية على ضفاف النيل.",
    characteristics: [
      "ظهور الزراعة والرعي",
      "تطور الفخار والحرف اليدوية",
      "نشوء المعتقدات الدينية الأولى",
      "التجارة بين المجتمعات",
    ],
    keyArtifacts: ["لوحة نارمر", "فخار نقادة", "تماثيل العاج"],
    relatedPageLink: undefined,
  },
  {
    id: "early-dynastic",
    nameAr: "عصر الأسرات المبكرة",
    nameEn: "Early Dynastic Period",
    startYear: -3100,
    endYear: -2686,
    dynasties: [
      {
        number: 1,
        nameAr: "الأسرة الأولى",
        nameEn: "First Dynasty",
        startYear: -3100,
        endYear: -2890,
        capital: "ثينيس",
        notableRulers: ["نارمر", "مينا", "جر", "جت"],
        keyEvents: ["توحيد مصر العليا والسفلى", "تأسيس الكتابة الهيروغليفية"],
      },
      {
        number: 2,
        nameAr: "الأسرة الثانية",
        nameEn: "Second Dynasty",
        startYear: -2890,
        endYear: -2686,
        capital: "ثينيس",
        notableRulers: ["رانب", "نيتجريخت", "خاسخموي"],
        keyEvents: ["تطوير الكتابة", "بناء المقابر الملكية في أبيدوس"],
      },
    ],
    description:
      "مرحلة توحيد مصر وتأسيس الدولة المركزية، شهدت نشوء الكتابة الهيروغليفية وتطور الفن والعمارة الملكية.",
    characteristics: [
      "توحيد مصر العليا والسفلى",
      "نشوء الكتابة الهيروغليفية",
      "تطور العمارة الجنائزية",
      "مركزية السلطة الملكية",
    ],
    keyArtifacts: ["لوحة نارمر", "مقابر أبيدوس", "ألواح العاج"],
    relatedPageLink: undefined,
  },
  {
    id: "old-kingdom",
    nameAr: "الدولة القديمة",
    nameEn: "Old Kingdom",
    startYear: -2686,
    endYear: -2181,
    dynasties: [
      {
        number: 3,
        nameAr: "الأسرة الثالثة",
        nameEn: "Third Dynasty",
        startYear: -2686,
        endYear: -2613,
        capital: "منف",
        notableRulers: ["زوسر", "سنفرو"],
        keyEvents: ["بناء هرم زوسر المدرج", "تطور العمارة الحجرية"],
      },
      {
        number: 4,
        nameAr: "الأسرة الرابعة",
        nameEn: "Fourth Dynasty",
        startYear: -2613,
        endYear: -2494,
        capital: "منف",
        notableRulers: ["خوفو", "خفرع", "منقرع"],
        keyEvents: ["بناء أهرامات الجيزة الكبرى", "نحت أبو الهول"],
      },
      {
        number: 5,
        nameAr: "الأسرة الخامسة",
        nameEn: "Fifth Dynasty",
        startYear: -2494,
        endYear: -2345,
        capital: "منف",
        notableRulers: ["أوسركاف", "ساحورع", "أوناس"],
        keyEvents: ["بناء معابد الشمس", "نصوص الأهرام"],
      },
      {
        number: 6,
        nameAr: "الأسرة السادسة",
        nameEn: "Sixth Dynasty",
        startYear: -2345,
        endYear: -2181,
        capital: "منف",
        notableRulers: ["تيتي", "بيبي الأول", "بيبي الثاني"],
        keyEvents: ["توسع الحكم المحلي", "حملات نوبيا"],
      },
    ],
    description:
      "عصر ازدهار الحضارة المصرية وبناء الأهرامات الكبرى، يُعدّ من أعظم العصور في تاريخ مصر القديمة حيث بلغت العمارة والفنون ذروتها.",
    characteristics: [
      "بناء الأهرامات الكبرى",
      "مركزية الحكم الفرعوني",
      "ازدهار الفنون والنحت",
      "تطور الكتابة الهيروغليفية",
      "نصوص الأهرام",
    ],
    keyArtifacts: ["تمثال خوفو العاجي", "أبو الهول", "نصوص الأهرام", "تمثال خفرع"],
    relatedPageLink: undefined,
  },
  {
    id: "first-intermediate",
    nameAr: "عصر الانتقال الأول",
    nameEn: "First Intermediate Period",
    startYear: -2181,
    endYear: -2055,
    dynasties: [
      {
        number: 7,
        nameAr: "الأسرة السابعة",
        nameEn: "Seventh Dynasty",
        startYear: -2181,
        endYear: -2160,
        capital: "منف",
        notableRulers: [],
        keyEvents: ["انهيار السلطة المركزية"],
      },
      {
        number: 8,
        nameAr: "الأسرة الثامنة",
        nameEn: "Eighth Dynasty",
        startYear: -2160,
        endYear: -2130,
        capital: "منف",
        notableRulers: [],
        keyEvents: ["تفكك الدولة المركزية"],
      },
    ],
    description:
      "مرحلة تفكك السلطة المركزية وظهور الحكام المحليين، شهدت صراعات سياسية وتراجعاً في الإنتاج الفني والمعماري.",
    characteristics: [
      "تفكك السلطة المركزية",
      "ظهور الحكام المحليين",
      "صراعات سياسية",
      "تراجع الإنتاج الفني",
    ],
    keyArtifacts: ["توابيت الخشب المزخرفة", "نصوص التوابيت"],
    relatedPageLink: undefined,
  },
  {
    id: "middle-kingdom",
    nameAr: "الدولة الوسطى",
    nameEn: "Middle Kingdom",
    startYear: -2055,
    endYear: -1650,
    dynasties: [
      {
        number: 11,
        nameAr: "الأسرة الحادية عشرة",
        nameEn: "Eleventh Dynasty",
        startYear: -2055,
        endYear: -1985,
        capital: "طيبة",
        notableRulers: ["منتوحتب الثاني", "منتوحتب الثالث"],
        keyEvents: ["إعادة توحيد مصر", "بناء معبد الدير البحري"],
      },
      {
        number: 12,
        nameAr: "الأسرة الثانية عشرة",
        nameEn: "Twelfth Dynasty",
        startYear: -1985,
        endYear: -1773,
        capital: "إيتاوي",
        notableRulers: ["أمنمحات الأول", "سنوسرت الثالث", "أمنمحات الثالث"],
        keyEvents: ["ازدهار الأدب المصري", "توسع في النوبة", "مشاريع الري"],
      },
    ],
    description:
      "عصر إعادة التوحيد والازدهار الثقافي، شهد ازدهار الأدب والفنون وتوسع النفوذ المصري في النوبة وبلاد الشام.",
    characteristics: [
      "إعادة توحيد مصر",
      "ازدهار الأدب والشعر",
      "توسع في النوبة",
      "تطور الفنون والنحت",
      "مشاريع الري الكبرى",
    ],
    keyArtifacts: ["تمثال سنوسرت الثالث", "مجوهرات الأميرات", "قصة سنوهي"],
    relatedPageLink: undefined,
  },
  {
    id: "second-intermediate",
    nameAr: "عصر الانتقال الثاني",
    nameEn: "Second Intermediate Period",
    startYear: -1650,
    endYear: -1550,
    dynasties: [
      {
        number: 15,
        nameAr: "الأسرة الخامسة عشرة (الهكسوس)",
        nameEn: "Fifteenth Dynasty (Hyksos)",
        startYear: -1650,
        endYear: -1550,
        capital: "أواريس",
        notableRulers: ["أبوفيس"],
        keyEvents: ["غزو الهكسوس لمصر", "إدخال الحصان والعجلة الحربية"],
      },
    ],
    description:
      "مرحلة حكم الهكسوس لشمال مصر، أدخلوا تقنيات جديدة كالحصان والعجلة الحربية، وشهدت المقاومة المصرية من الجنوب.",
    characteristics: [
      "حكم الهكسوس لشمال مصر",
      "إدخال الحصان والعجلة الحربية",
      "تأثيرات ثقافية أجنبية",
      "المقاومة المصرية من طيبة",
    ],
    keyArtifacts: ["أسلحة الهكسوس", "الخزف الكنعاني"],
    relatedPageLink: undefined,
  },
  {
    id: "new-kingdom",
    nameAr: "الدولة الحديثة",
    nameEn: "New Kingdom",
    startYear: -1550,
    endYear: -1069,
    dynasties: [
      {
        number: 18,
        nameAr: "الأسرة الثامنة عشرة",
        nameEn: "Eighteenth Dynasty",
        startYear: -1550,
        endYear: -1295,
        capital: "طيبة",
        notableRulers: ["أحمس الأول", "تحتمس الثالث", "أمنحتب الثالث", "أخناتون", "توت عنخ آمون"],
        keyEvents: ["طرد الهكسوس", "توسع الإمبراطورية", "ثورة أخناتون الدينية"],
      },
      {
        number: 19,
        nameAr: "الأسرة التاسعة عشرة",
        nameEn: "Nineteenth Dynasty",
        startYear: -1295,
        endYear: -1186,
        capital: "بي-رعمسيس",
        notableRulers: ["رمسيس الأول", "سيتي الأول", "رمسيس الثاني"],
        keyEvents: ["معركة قادش", "بناء أبو سمبل", "معاهدة السلام مع الحيثيين"],
      },
      {
        number: 20,
        nameAr: "الأسرة العشرون",
        nameEn: "Twentieth Dynasty",
        startYear: -1186,
        endYear: -1069,
        capital: "بي-رعمسيس",
        notableRulers: ["رمسيس الثالث", "رمسيس الرابع"],
        keyEvents: ["صد غزو شعوب البحر", "تراجع القوة المصرية"],
      },
    ],
    description:
      "أعظم عصور مصر القديمة، شهد توسع الإمبراطورية المصرية لتشمل النوبة وبلاد الشام، وبناء أعظم المعابد والمقابر.",
    characteristics: [
      "توسع الإمبراطورية المصرية",
      "بناء معابد الكرنك والأقصر",
      "وادي الملوك",
      "ازدهار الفنون والعمارة",
      "الدبلوماسية الدولية",
    ],
    keyArtifacts: ["كنوز توت عنخ آمون", "تمثال رمسيس الثاني", "بردية إيبرس"],
    relatedPageLink: undefined,
  },
  {
    id: "third-intermediate",
    nameAr: "عصر الانتقال الثالث",
    nameEn: "Third Intermediate Period",
    startYear: -1069,
    endYear: -664,
    dynasties: [
      {
        number: 21,
        nameAr: "الأسرة الحادية والعشرون",
        nameEn: "Twenty-First Dynasty",
        startYear: -1069,
        endYear: -945,
        capital: "تانيس",
        notableRulers: ["سمندس", "بسوسنس الأول"],
        keyEvents: ["انقسام مصر بين الشمال والجنوب"],
      },
      {
        number: 22,
        nameAr: "الأسرة الثانية والعشرون (الليبية)",
        nameEn: "Twenty-Second Dynasty (Libyan)",
        startYear: -945,
        endYear: -715,
        capital: "بوباستيس",
        notableRulers: ["شيشنق الأول", "أوسركون الثاني"],
        keyEvents: ["الحكم الليبي لمصر", "غزو فلسطين"],
      },
    ],
    description:
      "مرحلة تفكك سياسي وحكم أجنبي، شهدت تنافس الأسرات الليبية والنوبية على السلطة في مصر.",
    characteristics: [
      "تفكك سياسي",
      "حكم الأسرات الليبية",
      "تنافس على السلطة",
      "استمرار التقاليد الدينية",
    ],
    keyArtifacts: ["مجوهرات تانيس", "توابيت الكهنة"],
    relatedPageLink: undefined,
  },
  {
    id: "late-period",
    nameAr: "العصر المتأخر",
    nameEn: "Late Period",
    startYear: -664,
    endYear: -332,
    dynasties: [
      {
        number: 26,
        nameAr: "الأسرة السادسة والعشرون (الصاوية)",
        nameEn: "Twenty-Sixth Dynasty (Saite)",
        startYear: -664,
        endYear: -525,
        capital: "صا الحجر",
        notableRulers: ["بسماتيك الأول", "نخاو الثاني", "أحمس الثاني"],
        keyEvents: ["إعادة توحيد مصر", "الانفتاح على اليونان", "ازدهار التجارة"],
      },
      {
        number: 30,
        nameAr: "الأسرة الثلاثون",
        nameEn: "Thirtieth Dynasty",
        startYear: -380,
        endYear: -343,
        capital: "سبنيتوس",
        notableRulers: ["نختنبو الأول", "نختنبو الثاني"],
        keyEvents: ["آخر الأسرات المصرية الأصيلة", "مقاومة الفرس"],
      },
    ],
    description:
      "آخر عصور مصر الفرعونية المستقلة، شهد تناوب الحكم بين الأسرات المصرية والفارسية، وازدهار الفنون في العصر الصاوي.",
    characteristics: [
      "إعادة الإحياء الثقافي",
      "الانفتاح على الحضارة اليونانية",
      "الحكم الفارسي",
      "آخر الأسرات المصرية الأصيلة",
    ],
    keyArtifacts: ["تماثيل العصر الصاوي", "الأوشابتي", "لوحة نيتوكريس"],
    relatedPageLink: undefined,
  },
  {
    id: "greco-roman",
    nameAr: "العصر اليوناني الروماني",
    nameEn: "Greco-Roman Period",
    startYear: -332,
    endYear: 641,
    dynasties: [
      {
        number: 0,
        nameAr: "الأسرة البطلمية",
        nameEn: "Ptolemaic Dynasty",
        startYear: -305,
        endYear: -30,
        capital: "الإسكندرية",
        notableRulers: ["بطليموس الأول", "كليوباترا السابعة"],
        keyEvents: ["تأسيس الإسكندرية", "مكتبة الإسكندرية", "مزج الثقافتين المصرية واليونانية"],
      },
    ],
    description:
      "عصر الحكم اليوناني والروماني لمصر، شهد مزجاً فريداً بين الحضارتين المصرية واليونانية، وتأسيس الإسكندرية مركزاً للعلم والثقافة.",
    characteristics: [
      "مزج الثقافتين المصرية واليونانية",
      "تأسيس الإسكندرية",
      "مكتبة الإسكندرية",
      "الفن الهلنستي المصري",
      "انتشار المسيحية",
    ],
    keyArtifacts: ["حجر رشيد", "تماثيل سيرابيس", "الفيوم البورتريه"],
    relatedPageLink: "/era/greco-roman",
  },
  {
    id: "islamic",
    nameAr: "العصر الإسلامي",
    nameEn: "Islamic Period",
    startYear: 641,
    endYear: 1517,
    dynasties: [
      {
        number: 0,
        nameAr: "الخلافة الراشدة والأموية",
        nameEn: "Rashidun and Umayyad Caliphate",
        startYear: 641,
        endYear: 750,
        capital: "الفسطاط",
        notableRulers: ["عمرو بن العاص"],
        keyEvents: ["الفتح الإسلامي لمصر", "تأسيس الفسطاط"],
      },
      {
        number: 1,
        nameAr: "الدولة الفاطمية",
        nameEn: "Fatimid Caliphate",
        startYear: 969,
        endYear: 1171,
        capital: "القاهرة",
        notableRulers: ["المعز لدين الله", "الحاكم بأمر الله"],
        keyEvents: ["تأسيس القاهرة", "بناء الأزهر", "ازدهار الفنون الإسلامية"],
      },
      {
        number: 2,
        nameAr: "الدولة الأيوبية",
        nameEn: "Ayyubid Dynasty",
        startYear: 1171,
        endYear: 1250,
        capital: "القاهرة",
        notableRulers: ["صلاح الدين الأيوبي"],
        keyEvents: ["بناء قلعة صلاح الدين", "الحروب الصليبية"],
      },
    ],
    description:
      "عصر الحضارة الإسلامية في مصر، شهد تأسيس القاهرة وازدهار الفنون والعمارة الإسلامية، وتطور المشربية كعنصر معماري فريد.",
    characteristics: [
      "تأسيس القاهرة الإسلامية",
      "ازدهار العمارة الإسلامية",
      "تطور المشربية والزخارف الهندسية",
      "الفنون الإسلامية",
      "مراكز العلم والتعليم",
    ],
    keyArtifacts: ["المشربية الخشبية", "الزخارف الهندسية", "الخط العربي", "الفسيفساء الإسلامية"],
    relatedPageLink: "/era/islamic",
  },
]
